// Generates the golden corpus: {input, expected} pairs from the TS converter.
import { markdownToHtml } from "/home/visi0n/Code/shalador-dev/leantime-mcp/src/markdown.ts";

const cases: [name: string, input: string][] = [
  ["empty", ""],
  ["single-para", "Simple text"],
  ["two-paras", "First\n\nSecond"],
  ["br", "line one\nline two"],
  ["h1", "# Title"],
  ["h2", "## Section"],
  ["h3", "### Sub"],
  ["h4", "#### Deep"],
  ["h5-clamp", "##### Five"],
  ["h6-clamp", "###### Six"],
  ["h7-para", "####### Seven"],
  ["hash-nospace", "#Not a heading"],
  ["bold", "**important**"],
  ["bold-dunder", "__important__"],
  ["bold-mid", "text **bold** rest"],
  ["italic", "*emphasis*"],
  ["italic-underscore", "text _ital_ rest"],
  ["italic-star-alone", "*star*"],
  ["strike", "~~obsolete~~"],
  ["snake-case", "use some_var_name here"],
  ["dunder-word", "dunder __init__ method"],
  ["inline-code", "run `npm test` now"],
  ["code-protects", "``**not bold**`` x"],
  ["code-triple", "``` `tick` ```"],
  ["code-unmatched", "a ` b"],
  ["code-inside-bold", "**bold `code` bold**"],
  ["link", "[docs](https://example.com)"],
  ["link-mailto", "mail [me](mailto:a@b.co)"],
  ["link-bad-scheme", "[x](javascript:alert(1))"],
  ["link-image", "![alt](https://example.com/i.png)"],
  ["link-in-bold", "**see [docs](https://x.io)**"],
  ["ul", "- one\n- two\n- three"],
  ["ul-star", "* one\n* two"],
  ["ol", "1. first\n2. second"],
  ["nested", "- top\n  - child\n- top2"],
  ["nested-deep", "- a\n  - b\n    - c\n- d"],
  ["nested-ordered-in-ul", "- top\n  1. sub1\n  2. sub2\n- top2"],
  ["task", "- [ ] todo\n- [x] done"],
  ["task-capital-x", "- [X] done too"],
  ["task-mixed-plain", "- [ ] a\n- plain b"],
  ["lazy-continuation", "- item text\ncontinues here\n- second"],
  ["hr", "---"],
  ["hr-four", "----"],
  ["hr-stars", "***"],
  ["hr-underscores", "___"],
  ["hr-spaces", "   ---   "],
  ["list-vs-hr", "- item"],
  ["quote", "> quoted text"],
  ["quote-two-paras", "> para one\n\n> para two"],
  ["quote-multiline", "> line a\n> line b"],
  ["quote-lazy", "> first\ncontinued quote"],
  ["fence-lang", "```ts\nconst x = 1;\n```"],
  ["fence-plain", "```\ncode line\n```"],
  ["fence-escapes", "```\n<script>alert(1)</script>\n```"],
  ["fence-unclosed", "```\nnever closed"],
  ["fence-close-trailing-space", "```\nx\n```   "],
  ["raw-html-escaped", "<b>not bold</b> & <i>tag</i>"],
  ["crlf", "a\r\n\r\nb"],
  ["crlf-list", "- a\r\n- b"],
  ["unicode", "Émotion **gras** à çà"],
  ["mixed-doc", ["## Objectif", "", "Livrer la **v1** avec `tests`.", "", "### Étapes", "", "1. setup", "2. build", "", "- [x] spec", "- [ ] merge", "", "> voir [docs](https://leantime.io)", "", "---", "", "Fin."].join("\n")],
  ["emphasis-boundary-paren", "(**bold in parens**)"],
  ["emphasis-no-boundary", "a**b**c"],
  ["emphasis-close-punct", "**bold.** next"],
  ["emphasis-inner-spaces", "** not bold **"],
  ["nested-em-in-strong", "**bold *ital* bold**"],
  ["underscore-in-words", "foo_bar_baz"],
  ["multiple-paragraphs-list", "- item one\n\n- item two"],
  ["hard-case-code-first", "`code` **bold** *ital* ~~~ x"],
  ["blockquote-nested-quote", "> a\n>\n> b"],
];

const out = cases.map(([name, input]) => ({ name, input, expected: markdownToHtml(input) }));
await Deno.writeTextFile("/tmp/opencode/md-golden.json", JSON.stringify(out, null, 2));
console.log(`Wrote ${out.length} cases`);
